// <auto-generated />
namespace OnlineBanking.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test));
        
        string IMigrationMetadata.Id
        {
            get { return "202108111334085_test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
